FROM node:20-alpine3.20 as build-stage

WORKDIR /app

COPY . .

RUN npm install
RUN npm run build

FROM nginx:1.26-alpine3.20-perl as running-stage

WORKDIR /usr/share/nginx/html

COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./nginx.default.conf /etc/nginx/conf.d/default.conf
COPY --from=build-stage /app/.output/public /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
