FROM node:20-alpine3.20 as build-stage

WORKDIR /app

COPY . .

RUN npm install
RUN npm run build

FROM node:20-alpine3.20 as running-stage

ENV NODE_ENV=production
ENV PORT=3000

WORKDIR /app

COPY --from=build-stage /app/.output /app/.output
COPY --from=build-stage /app/node_modules /app/node_modules

USER node

EXPOSE 3000
CMD ["sh", "-c", "node /app/.output/server/index.mjs"]
