export {};
declare global {
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Models =
  | UserRead
  | UserPreviewRead
  | UserCreate
  | UserLogin
  | UserChangeInfo
  | UserChangePassword
  | UserToken
  | UserTokenUpdate
  | UserPasswordResetRequest
  | UserPasswordResetConfirm
  | AdminUserRead
  | AdminUserUpdate
  | AdminUserListResponse
  | AdminDashboardStats
  | ImpersonationResponse
  | EventLogRead
  | EventLogFilter
  | EventLogListResponse;
export type Id = number;
export type Email = string;
export type FirstName = string;
export type LastName = string;
export type IsAdmin = boolean;
export type IsPremium = boolean;
export type Id1 = number;
export type FirstName1 = string;
export type LastName1 = string;
export type Email1 = string;
export type Password = string;
export type FirstName2 = string;
export type LastName2 = string;
export type Email2 = string;
export type Password1 = string;
export type FirstName3 = string;
export type LastName3 = string;
export type Email3 = string;
export type OldPassword = string;
export type NewPassword = string;
export type CreatedAt = string;
export type ExpiresAt = string;
export type RealAdminId = number | null;
export type AccessToken = string;
export type TokenType = string;
export type Email4 = string;
export type Email5 = string;
export type Password2 = string;
export type Token = string;
export type Id2 = number;
export type Email6 = string;
export type FirstName4 = string;
export type LastName4 = string;
export type IsAdmin1 = boolean;
export type IsPremium1 = boolean;
export type EmailConfirmed = boolean;
export type CreatedAt1 = string | null;
export type LastSeenAt = string | null;
export type FirstName5 = string | null;
export type LastName5 = string | null;
export type Email7 = string | null;
export type IsAdmin2 = boolean | null;
export type IsPremium2 = boolean | null;
export type Items = AdminUserRead[];
export type Total = number;
export type Limit = number;
export type Offset = number;
export type TotalUsers = number;
export type AdminUsers = number;
export type PremiumUsers = number;
export type Id3 = number;
export type UserId = number | null;
export type Action = string;
export type IpAddress = string | null;
export type UserAgent = string | null;
export type CreatedAt2 = string;
export type RecentEvents = EventLogRead[];
export type AccessToken1 = string;
export type Message = string;
export type UserId1 = number | null;
export type Action1 = string | null;
export type ActionPrefix = string | null;
export type FromDate = string | null;
export type ToDate = string | null;
export type Items1 = EventLogRead[];
export type Total1 = number;
export type Limit1 = number;
export type Offset1 = number;

export interface UserRead {
  id: Id;
  email: Email;
  first_name: FirstName;
  last_name: LastName;
  is_admin: IsAdmin;
  is_premium: IsPremium;
}
export interface UserPreviewRead {
  id: Id1;
  first_name: FirstName1;
  last_name: LastName1;
}
export interface UserCreate {
  email: Email1;
  password: Password;
  first_name: FirstName2;
  last_name: LastName2;
}
export interface UserLogin {
  email: Email2;
  password: Password1;
}
export interface UserChangeInfo {
  first_name: FirstName3;
  last_name: LastName3;
  email: Email3;
}
export interface UserChangePassword {
  old_password: OldPassword;
  new_password: NewPassword;
}
export interface UserToken {
  user: UserRead;
  created_at: CreatedAt;
  expires_at: ExpiresAt;
  real_admin_id?: RealAdminId;
}
export interface UserTokenUpdate {
  access_token: AccessToken;
  token_parsed: UserToken;
  user: UserRead;
  token_type?: TokenType;
}
export interface UserPasswordResetRequest {
  email: Email4;
}
export interface UserPasswordResetConfirm {
  email: Email5;
  password: Password2;
  token: Token;
}
/**
 * Extended user info for admin view.
 */
export interface AdminUserRead {
  id: Id2;
  email: Email6;
  first_name: FirstName4;
  last_name: LastName4;
  is_admin: IsAdmin1;
  is_premium: IsPremium1;
  email_confirmed: EmailConfirmed;
  created_at: CreatedAt1;
  last_seen_at: LastSeenAt;
}
/**
 * Schema for admin updating a user.
 */
export interface AdminUserUpdate {
  first_name?: FirstName5;
  last_name?: LastName5;
  email?: Email7;
  is_admin?: IsAdmin2;
  is_premium?: IsPremium2;
}
/**
 * Paginated response for user list.
 */
export interface AdminUserListResponse {
  items: Items;
  total: Total;
  limit: Limit;
  offset: Offset;
}
/**
 * Dashboard statistics.
 */
export interface AdminDashboardStats {
  total_users: TotalUsers;
  admin_users: AdminUsers;
  premium_users: PremiumUsers;
  recent_events: RecentEvents;
}
/**
 * Output schema for reading event logs.
 */
export interface EventLogRead {
  id: Id3;
  user_id: UserId;
  action: Action;
  details: Details;
  ip_address: IpAddress;
  user_agent: UserAgent;
  created_at: CreatedAt2;
}
export interface Details {
  [k: string]: unknown;
}
/**
 * Response for impersonation endpoints.
 */
export interface ImpersonationResponse {
  access_token: AccessToken1;
  token_parsed: UserToken;
  user: UserRead;
  message: Message;
}
/**
 * Query parameters for filtering event logs.
 */
export interface EventLogFilter {
  user_id?: UserId1;
  action?: Action1;
  action_prefix?: ActionPrefix;
  from_date?: FromDate;
  to_date?: ToDate;
}
/**
 * Paginated response for event logs.
 */
export interface EventLogListResponse {
  items: Items1;
  total: Total1;
  limit: Limit1;
  offset: Offset1;
}
}
