export {};
declare global {
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Models =
  | AuthMessageResponse
  | UserRead
  | UserPreviewRead
  | UserCreate
  | UserChangeEmail
  | UserChangeInfo
  | UserChangePassword
  | UserToken
  | UserTokenUpdate
  | UserPasswordResetRequest
  | AdminUserRead
  | AdminUserUpdate
  | AdminUserListResponse
  | AdminDashboardStats
  | ImpersonationResponse
  | EventLogRead
  | EventLogFilter
  | EventLogListResponse
  | BackupInfo
  | BackupListResponse
  | BillingPortalResponse
  | SubscriptionStatus
  | DatabaseHealthResponse
  | TableStats
  | IndexStats
  | Recommendation
  | OrganizationRead
  | OrganizationCreate
  | OrganizationUpdate
  | OrganizationListResponse
  | OrganizationMemberRead
  | OrganizationMemberAdd
  | OrganizationMemberUpdate
  | OrganizationMemberListResponse
  | OrganizationPlan
  | OrganizationCheckoutRequest
  | OrganizationCheckoutResponse
  | OrganizationSubscriptionStatus
  | UserOrganizationInfo
  | OAuthStatusResponse
  | OAuthUrlResponse
  | OAuthCallbackRequest
  | ConversationCreate
  | ConversationRead
  | ConversationDetail
  | ConversationListResponse
  | ConversationUserPreview
  | MessageCreate
  | MessageRead
  | MessageListResponse
  | OrganizationCustomData;
export type Message = string;
export type Id = number;
export type Email = string;
export type FirstName = string;
export type LastName = string;
export type IsAdmin = boolean;
export type IsPremium = boolean;
export type HasPersonalSubscription = boolean;
export type OrganizationId = number;
export type OrganizationName = string;
export type IsAdmin1 = boolean;
export type HasPremiumSeat = boolean;
export type Organizations = UserOrganizationInfo[];
export type Id1 = number;
export type FirstName1 = string;
export type LastName1 = string;
export type Email1 = string;
export type Password = string;
export type FirstName2 = string;
export type LastName2 = string;
export type NewEmail = string;
export type Password1 = string;
export type FirstName3 = string;
export type LastName3 = string;
export type OldPassword = string;
export type NewPassword = string;
export type CreatedAt = string;
export type ExpiresAt = string;
export type RealAdminId = number | null;
export type AccessToken = string;
export type TokenType = string;
export type Email2 = string;
export type Id2 = number;
export type Email3 = string;
export type FirstName4 = string;
export type LastName4 = string;
export type IsAdmin2 = boolean;
export type IsPremium1 = boolean;
export type EmailConfirmed = boolean;
export type CreatedAt1 = string | null;
export type DeletedAt = string | null;
export type FirstName5 = string | null;
export type LastName5 = string | null;
export type Email4 = string | null;
export type IsAdmin3 = boolean | null;
export type IsPremium2 = boolean | null;
export type Items = AdminUserRead[];
export type Total = number;
export type Limit = number;
export type Offset = number;
export type TotalUsers = number;
export type AdminUsers = number;
export type PremiumUsers = number;
export type Id3 = number;
export type UserId = number | null;
export type Action = string;
export type Details = {
  [k: string]: unknown;
} | null;
export type IpAddress = string | null;
export type UserAgent = string | null;
export type CreatedAt2 = string | null;
export type RecentEvents = EventLogRead[];
export type AccessToken1 = string;
export type Message1 = string;
export type UserId1 = number | null;
export type Action1 = string | null;
export type ActionPrefix = string | null;
export type FromDate = string | null;
export type ToDate = string | null;
export type Items1 = EventLogRead[];
export type Total1 = number;
export type Limit1 = number;
export type Offset1 = number;
export type Filename = string;
export type Size = number;
export type CreatedAt3 = string;
export type Items2 = BackupInfo[];
export type Total2 = number;
export type Url = string;
export type IsPremium3 = boolean;
export type Plan = string | null;
export type ExpiresAt1 = string | null;
export type CancelAtPeriodEnd = boolean;
export type DatabaseSize = number;
export type DatabaseSizePretty = string;
export type ActiveConnections = number;
export type MaxConnections = number;
export type CacheHitRatio = number;
export type Name = string;
export type Size1 = number;
export type SizePretty = string;
export type RowCount = number;
export type DeadTuples = number;
export type SeqScans = number;
export type IdxScans = number;
export type LastVacuum = string | null;
export type Tables = TableStats[];
export type Name1 = string;
export type Table = string;
export type Size2 = number;
export type SizePretty1 = string;
export type Scans = number;
export type IsUnused = boolean;
export type Indexes = IndexStats[];
export type Type = string;
export type Severity = string;
export type Table1 = string | null;
export type Message2 = string;
export type Action2 = string;
export type Recommendations = Recommendation[];
export type Id4 = number;
export type Name2 = string;
export type Email5 = string;
export type Description = string | null;
export type Phone = string | null;
export type TaxNumber = string | null;
export type AddressLine1 = string | null;
export type AddressLine2 = string | null;
export type City = string | null;
export type State = string | null;
export type PostalCode = string | null;
export type Country = string | null;
export type StripeId = string | null;
export type StripePremium = boolean;
export type StripeQuota = number;
export type CreatedAt4 = string | null;
export type DeletedAt1 = string | null;
export type MemberCount = number;
export type PremiumMemberCount = number;
export type UserId2 = number;
export type Email6 = string;
export type FirstName6 = string;
export type LastName6 = string;
export type IsAdmin4 = boolean;
export type IsPremium4 = boolean;
export type HasPremiumSeat1 = boolean;
export type JoinedAt = string | null;
export type Members = OrganizationMemberRead[];
export type Description1 = string | null;
export type Phone1 = string | null;
export type TaxNumber1 = string | null;
export type AddressLine11 = string | null;
export type AddressLine21 = string | null;
export type City1 = string | null;
export type State1 = string | null;
export type PostalCode1 = string | null;
export type Country1 = string | null;
export type CustomData1 = {
  [k: string]: unknown;
} | null;
export type Name3 = string;
export type Email7 = string;
export type Description2 = string | null;
export type Phone2 = string | null;
export type TaxNumber2 = string | null;
export type AddressLine12 = string | null;
export type AddressLine22 = string | null;
export type City2 = string | null;
export type State2 = string | null;
export type PostalCode2 = string | null;
export type Country2 = string | null;
export type CustomData2 = {
  [k: string]: unknown;
} | null;
export type Name4 = string | null;
export type Email8 = string | null;
export type Items3 = OrganizationRead[];
export type Total3 = number;
export type Page = number;
export type PerPage = number;
export type Email9 = string;
export type IsAdmin5 = boolean;
export type IsAdmin6 = boolean | null;
export type IsPremium5 = boolean | null;
export type Items4 = OrganizationMemberRead[];
export type Total4 = number;
export type Page1 = number;
export type PerPage1 = number;
export type PriceId = string;
export type Name5 = string;
export type Amount = number;
export type Currency = string;
export type Seats = number;
export type Interval = string;
export type PriceId1 = string;
export type Url1 = string;
export type StripePremium1 = boolean;
export type StripeQuota1 = number;
export type CancelAtPeriodEnd1 = boolean;
export type ExpiresAt2 = string | null;
export type Enabled = boolean;
export type Providers = string[];
export type Url2 = string;
export type State3 = string;
export type Code = string;
export type State4 = string;
export type Subject = string;
export type Content = string;
export type Id5 = number;
export type Type1 = string;
export type Subject1 = string | null;
export type CreatedById = number | null;
export type Id6 = number;
export type Email10 = string;
export type FirstName7 = string;
export type LastName7 = string;
export type IsClosed = boolean;
export type ClosedAt = string | null;
export type CreatedAt5 = string | null;
export type UpdatedAt = string | null;
export type UnreadCount = number;
export type Id7 = number;
export type ConversationId = number;
export type SenderId = number | null;
export type Content1 = string;
export type IsAdminResponse = boolean;
export type CreatedAt6 = string | null;
export type Id8 = number;
export type Type2 = string;
export type Subject2 = string | null;
export type CreatedById1 = number | null;
export type IsClosed1 = boolean;
export type ClosedAt1 = string | null;
export type CreatedAt7 = string | null;
export type UpdatedAt1 = string | null;
export type UnreadCount1 = number;
export type Messages = MessageRead[];
export type Items5 = ConversationRead[];
export type Total5 = number;
export type Limit2 = number;
export type Offset2 = number;
export type Content2 = string;
export type Items6 = MessageRead[];
export type Total6 = number;
export type Limit3 = number;
export type Offset3 = number;
export type HasMore = boolean;

/**
 * Standard response for auth operations.
 */
export interface AuthMessageResponse {
  message: Message;
}
export interface UserRead {
  id: Id;
  email: Email;
  first_name: FirstName;
  last_name: LastName;
  is_admin: IsAdmin;
  is_premium: IsPremium;
  has_personal_subscription?: HasPersonalSubscription;
  organizations?: Organizations;
}
/**
 * Organization info for a user's memberships.
 */
export interface UserOrganizationInfo {
  organization_id: OrganizationId;
  organization_name: OrganizationName;
  is_admin: IsAdmin1;
  has_premium_seat?: HasPremiumSeat;
}
export interface UserPreviewRead {
  id: Id1;
  first_name: FirstName1;
  last_name: LastName1;
}
export interface UserCreate {
  email: Email1;
  password: Password;
  first_name: FirstName2;
  last_name: LastName2;
}
export interface UserChangeEmail {
  new_email: NewEmail;
  password: Password1;
}
export interface UserChangeInfo {
  first_name: FirstName3;
  last_name: LastName3;
}
export interface UserChangePassword {
  old_password: OldPassword;
  new_password: NewPassword;
}
export interface UserToken {
  user: UserRead;
  created_at: CreatedAt;
  expires_at: ExpiresAt;
  real_admin_id?: RealAdminId;
}
export interface UserTokenUpdate {
  access_token: AccessToken;
  token_parsed: UserToken;
  user: UserRead;
  token_type?: TokenType;
}
export interface UserPasswordResetRequest {
  email: Email2;
}
/**
 * Extended user info for admin view.
 */
export interface AdminUserRead {
  id: Id2;
  email: Email3;
  first_name: FirstName4;
  last_name: LastName4;
  is_admin: IsAdmin2;
  is_premium: IsPremium1;
  email_confirmed: EmailConfirmed;
  created_at: CreatedAt1;
  deleted_at?: DeletedAt;
}
/**
 * Schema for admin updating a user.
 */
export interface AdminUserUpdate {
  first_name?: FirstName5;
  last_name?: LastName5;
  email?: Email4;
  is_admin?: IsAdmin3;
  is_premium?: IsPremium2;
}
/**
 * Paginated response for user list.
 */
export interface AdminUserListResponse {
  items: Items;
  total: Total;
  limit: Limit;
  offset: Offset;
}
/**
 * Dashboard statistics.
 */
export interface AdminDashboardStats {
  total_users: TotalUsers;
  admin_users: AdminUsers;
  premium_users: PremiumUsers;
  recent_events: RecentEvents;
}
/**
 * Output schema for reading event logs.
 */
export interface EventLogRead {
  id: Id3;
  user_id: UserId;
  action: Action;
  details?: Details;
  ip_address: IpAddress;
  user_agent: UserAgent;
  created_at: CreatedAt2;
}
/**
 * Response for impersonation endpoints.
 */
export interface ImpersonationResponse {
  access_token: AccessToken1;
  token_parsed: UserToken;
  user: UserRead;
  message: Message1;
}
/**
 * Query parameters for filtering event logs.
 */
export interface EventLogFilter {
  user_id?: UserId1;
  action?: Action1;
  action_prefix?: ActionPrefix;
  from_date?: FromDate;
  to_date?: ToDate;
}
/**
 * Paginated response for event logs.
 */
export interface EventLogListResponse {
  items: Items1;
  total: Total1;
  limit: Limit1;
  offset: Offset1;
}
/**
 * Information about a single backup file.
 */
export interface BackupInfo {
  filename: Filename;
  size: Size;
  created_at: CreatedAt3;
}
/**
 * Response for backup list endpoint.
 */
export interface BackupListResponse {
  items: Items2;
  total: Total2;
}
/**
 * Response from billing portal endpoint.
 */
export interface BillingPortalResponse {
  url: Url;
}
/**
 * Current user's subscription status.
 */
export interface SubscriptionStatus {
  is_premium: IsPremium3;
  plan: Plan;
  expires_at: ExpiresAt1;
  cancel_at_period_end?: CancelAtPeriodEnd;
}
/**
 * Complete database health response.
 */
export interface DatabaseHealthResponse {
  database_size: DatabaseSize;
  database_size_pretty: DatabaseSizePretty;
  active_connections: ActiveConnections;
  max_connections: MaxConnections;
  cache_hit_ratio: CacheHitRatio;
  tables: Tables;
  indexes: Indexes;
  recommendations: Recommendations;
}
/**
 * Statistics for a database table.
 */
export interface TableStats {
  name: Name;
  size: Size1;
  size_pretty: SizePretty;
  row_count: RowCount;
  dead_tuples: DeadTuples;
  seq_scans: SeqScans;
  idx_scans: IdxScans;
  last_vacuum: LastVacuum;
}
/**
 * Statistics for a database index.
 */
export interface IndexStats {
  name: Name1;
  table: Table;
  size: Size2;
  size_pretty: SizePretty1;
  scans: Scans;
  is_unused: IsUnused;
}
/**
 * An actionable recommendation for database optimization.
 */
export interface Recommendation {
  type: Type;
  severity: Severity;
  table: Table1;
  message: Message2;
  action: Action2;
}
/**
 * Schema for reading organization info.
 */
export interface OrganizationRead {
  id: Id4;
  name: Name2;
  email: Email5;
  description?: Description;
  phone?: Phone;
  tax_number?: TaxNumber;
  address_line1?: AddressLine1;
  address_line2?: AddressLine2;
  city?: City;
  state?: State;
  postal_code?: PostalCode;
  country?: Country;
  custom_data?: CustomData;
  stripe_id?: StripeId;
  stripe_premium: StripePremium;
  stripe_quota: StripeQuota;
  created_at?: CreatedAt4;
  deleted_at?: DeletedAt1;
  member_count?: MemberCount;
  premium_member_count?: PremiumMemberCount;
  members?: Members;
}
export interface CustomData {
  [k: string]: unknown;
}
/**
 * Schema for reading organization member info.
 */
export interface OrganizationMemberRead {
  user_id: UserId2;
  email: Email6;
  first_name: FirstName6;
  last_name: LastName6;
  is_admin: IsAdmin4;
  is_premium: IsPremium4;
  has_premium_seat?: HasPremiumSeat1;
  joined_at?: JoinedAt;
}
/**
 * Schema for creating a new organization.
 */
export interface OrganizationCreate {
  description?: Description1;
  phone?: Phone1;
  tax_number?: TaxNumber1;
  address_line1?: AddressLine11;
  address_line2?: AddressLine21;
  city?: City1;
  state?: State1;
  postal_code?: PostalCode1;
  country?: Country1;
  custom_data?: CustomData1;
  name: Name3;
  email: Email7;
}
/**
 * Schema for updating an organization.
 */
export interface OrganizationUpdate {
  description?: Description2;
  phone?: Phone2;
  tax_number?: TaxNumber2;
  address_line1?: AddressLine12;
  address_line2?: AddressLine22;
  city?: City2;
  state?: State2;
  postal_code?: PostalCode2;
  country?: Country2;
  custom_data?: CustomData2;
  name?: Name4;
  email?: Email8;
}
/**
 * Paginated response for organization list.
 */
export interface OrganizationListResponse {
  items: Items3;
  total: Total3;
  page: Page;
  per_page: PerPage;
}
/**
 * Schema for adding a member by email.
 */
export interface OrganizationMemberAdd {
  email: Email9;
  is_admin?: IsAdmin5;
}
/**
 * Schema for updating a member's status.
 */
export interface OrganizationMemberUpdate {
  is_admin?: IsAdmin6;
  is_premium?: IsPremium5;
}
/**
 * Paginated response for member list.
 */
export interface OrganizationMemberListResponse {
  items: Items4;
  total: Total4;
  page: Page1;
  per_page: PerPage1;
}
/**
 * Schema for available organization plans.
 */
export interface OrganizationPlan {
  price_id: PriceId;
  name: Name5;
  amount: Amount;
  currency: Currency;
  seats: Seats;
  interval: Interval;
}
/**
 * Schema for creating a checkout session.
 */
export interface OrganizationCheckoutRequest {
  price_id: PriceId1;
}
/**
 * Schema for checkout session response.
 */
export interface OrganizationCheckoutResponse {
  url: Url1;
}
/**
 * Schema for organization subscription status (synced from Stripe).
 */
export interface OrganizationSubscriptionStatus {
  stripe_premium: StripePremium1;
  stripe_quota: StripeQuota1;
  cancel_at_period_end?: CancelAtPeriodEnd1;
  expires_at?: ExpiresAt2;
}
/**
 * Response indicating OAuth availability.
 */
export interface OAuthStatusResponse {
  enabled: Enabled;
  providers: Providers;
}
/**
 * Response containing the OAuth authorization URL.
 */
export interface OAuthUrlResponse {
  url: Url2;
  state: State3;
}
/**
 * Request body for OAuth callback.
 */
export interface OAuthCallbackRequest {
  code: Code;
  state: State4;
}
/**
 * Schema for creating a new support conversation.
 */
export interface ConversationCreate {
  subject: Subject;
  content: Content;
}
/**
 * Schema for reading a conversation.
 */
export interface ConversationRead {
  id: Id5;
  type: Type1;
  subject?: Subject1;
  created_by_id?: CreatedById;
  created_by?: ConversationUserPreview | null;
  is_closed?: IsClosed;
  closed_at?: ClosedAt;
  created_at?: CreatedAt5;
  updated_at?: UpdatedAt;
  unread_count?: UnreadCount;
  last_message?: MessageRead | null;
}
/**
 * User preview for conversation context, includes email for admin visibility.
 */
export interface ConversationUserPreview {
  id: Id6;
  email: Email10;
  first_name: FirstName7;
  last_name: LastName7;
}
/**
 * Schema for reading a message.
 */
export interface MessageRead {
  id: Id7;
  conversation_id: ConversationId;
  sender_id: SenderId;
  sender?: ConversationUserPreview | null;
  content: Content1;
  is_admin_response?: IsAdminResponse;
  created_at?: CreatedAt6;
}
/**
 * Schema for conversation with messages.
 */
export interface ConversationDetail {
  id: Id8;
  type: Type2;
  subject?: Subject2;
  created_by_id?: CreatedById1;
  created_by?: ConversationUserPreview | null;
  is_closed?: IsClosed1;
  closed_at?: ClosedAt1;
  created_at?: CreatedAt7;
  updated_at?: UpdatedAt1;
  unread_count?: UnreadCount1;
  last_message?: MessageRead | null;
  messages?: Messages;
}
/**
 * Paginated response for conversation list.
 */
export interface ConversationListResponse {
  items: Items5;
  total: Total5;
  limit: Limit2;
  offset: Offset2;
}
/**
 * Schema for creating a new message.
 */
export interface MessageCreate {
  content: Content2;
}
/**
 * Paginated response for messages in a conversation.
 */
export interface MessageListResponse {
  items: Items6;
  total: Total6;
  limit: Limit3;
  offset: Offset3;
  has_more: HasMore;
}
/**
 * Custom fields for organizations. Add your project-specific fields here.
 */
export interface OrganizationCustomData {}
}
