export { };
declare global {
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Models =
  | UserRead
  | UserPreviewRead
  | UserCreate
  | UserLogin
  | UserChangeInfo
  | UserChangePassword
  | UserToken
  | UserTokenUpdate
  | UserPasswordResetRequest
  | UserPasswordResetConfirm;
export type Id = number;
export type Email = string;
export type FirstName = string;
export type LastName = string;
export type IsAdmin = boolean;
export type Id1 = number;
export type FirstName1 = string;
export type LastName1 = string;
export type Email1 = string;
export type Password = string;
export type FirstName2 = string;
export type LastName2 = string;
export type Email2 = string;
export type Password1 = string;
export type FirstName3 = string;
export type LastName3 = string;
export type Email3 = string;
export type OldPassword = string;
export type NewPassword = string;
export type CreatedAt = string;
export type ExpiresAt = string;
export type AccessToken = string;
export type TokenType = string;
export type Email4 = string;
export type Email5 = string;
export type Password2 = string;
export type Token = string;

export interface UserRead {
  id: Id;
  email: Email;
  first_name: FirstName;
  last_name: LastName;
  is_admin: IsAdmin;
}
export interface UserPreviewRead {
  id: Id1;
  first_name: FirstName1;
  last_name: LastName1;
}
export interface UserCreate {
  email: Email1;
  password: Password;
  first_name: FirstName2;
  last_name: LastName2;
}
export interface UserLogin {
  email: Email2;
  password: Password1;
}
export interface UserChangeInfo {
  first_name: FirstName3;
  last_name: LastName3;
  email: Email3;
}
export interface UserChangePassword {
  old_password: OldPassword;
  new_password: NewPassword;
}
export interface UserToken {
  user: UserRead;
  created_at: CreatedAt;
  expires_at: ExpiresAt;
}
export interface UserTokenUpdate {
  access_token: AccessToken;
  token_parsed: UserToken;
  user: UserRead;
  token_type?: TokenType;
}
export interface UserPasswordResetRequest {
  email: Email4;
}
export interface UserPasswordResetConfirm {
  email: Email5;
  password: Password2;
  token: Token;
}
}
