#!/bin/bash
# ⚠️ STARTERPACK CORE — DO NOT MODIFY. This file is managed by the starterpack.
#
# Interactive wizard: set up an nginx host reverse proxy in front of the
# starterpack so the backend sees the real client IP instead of the Docker
# gateway. Generates the nginx site config, patches .env, validates, reloads.
#
# Background + manual steps: docs/deployment/reverse-proxy.md

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/utils.sh"
cd "$SCRIPT_DIR/../.."

# --- helpers ---------------------------------------------------------------

ask() {
    # ask "Prompt" ["default"] -> echoes the answer
    local prompt="$1" default="${2:-}" reply
    if [ -n "$default" ]; then
        read -r -p "$(echo -e "${BLUE}?${NC} ${prompt} [${default}]: ")" reply
        echo "${reply:-$default}"
    else
        read -r -p "$(echo -e "${BLUE}?${NC} ${prompt}: ")" reply
        echo "$reply"
    fi
}

confirm() {
    # confirm "Prompt" [default y|n] -> returns 0 for yes
    local prompt="$1" default="${2:-y}" reply hint="[Y/n]"
    [ "$default" = "n" ] && hint="[y/N]"
    read -r -p "$(echo -e "${BLUE}?${NC} ${prompt} ${hint} ")" reply
    reply="${reply:-$default}"
    [[ "$reply" =~ ^[Yy] ]]
}

# Set KEY=VALUE in .env, replacing an existing line or appending.
set_env() {
    local key="$1" value="$2"
    if grep -qE "^${key}=" .env; then
        # Use a temp file to avoid sed delimiter issues with the value.
        awk -v k="$key" -v v="$value" \
            'BEGIN{FS=OFS="="} $1==k{print k"="v; next} {print}' .env > .env.tmp
        mv .env.tmp .env
    else
        echo "${key}=${value}" >> .env
    fi
}

# Cloudflare's published ranges, fetched live. No baked-in fallback: a stale
# hardcoded list silently breaks real-IP restoration, so we fail loudly instead.
fetch_cf_ranges() {
    local v4 v6
    v4=$(curl -fsSL --max-time 5 https://www.cloudflare.com/ips-v4 2>/dev/null || true)
    v6=$(curl -fsSL --max-time 5 https://www.cloudflare.com/ips-v6 2>/dev/null || true)
    if [ -z "$v4" ]; then
        print_error "Couldn't fetch Cloudflare ranges from cloudflare.com/ips-v4. Check connectivity and retry." >&2
        return 1
    fi
    printf '%s\n%s\n' "$v4" "$v6"
}

# --- preflight -------------------------------------------------------------

[ -f .env ] || { print_error ".env not found. Run 'npm run setup' first."; exit 1; }
command -v nginx >/dev/null 2>&1 || { print_error "nginx is not installed on this host."; exit 1; }

set -a && source .env && set +a
PUBLIC_PORT="${PUBLIC_PORT:-80}"

SUDO=""
[ -w /etc/nginx ] || SUDO="sudo"

echo ""
print_info "This sets up nginx in front of the prod stack and points the app at the real client IP."
echo ""

# --- gather answers --------------------------------------------------------

DOMAIN="$(ask "Public domain (server_name), e.g. app.example.com")"
[ -n "$DOMAIN" ] || { print_error "A domain is required."; exit 1; }

CF=0
confirm "Is Cloudflare in front of this server?" && CF=1

if ! confirm "Proxy to the prod stack on 127.0.0.1:${PUBLIC_PORT} (PUBLIC_PORT from .env)?"; then
    PUBLIC_PORT="$(ask "Port the prod Traefik publishes on")"
fi

# Detect nginx layout.
if [ -d /etc/nginx/sites-available ]; then
    SITE_FILE="/etc/nginx/sites-available/${DOMAIN}"
    ENABLED_LINK="/etc/nginx/sites-enabled/${DOMAIN}"
elif [ -d /etc/nginx/conf.d ]; then
    SITE_FILE="/etc/nginx/conf.d/${DOMAIN}.conf"
    ENABLED_LINK=""
else
    print_error "Neither /etc/nginx/sites-available nor /etc/nginx/conf.d exists. Unrecognized nginx layout."
    exit 1
fi
REALIP_FILE="/etc/nginx/conf.d/cloudflare-realip.conf"

# --- build configs ---------------------------------------------------------

if [ "$CF" = 1 ]; then
    XFP="https"   # Cloudflare terminates TLS to the visitor
else
    XFP='$scheme'
fi

SERVER_CONF="$(cat <<EOF
# Generated by scripts/_core/setup-host-proxy.sh — safe to edit (app-owned on the host).
server {
    listen 80;
    server_name ${DOMAIN};
    client_max_body_size 16M;

    location / {
        proxy_pass http://127.0.0.1:${PUBLIC_PORT};
        proxy_set_header Host              \$host;
        proxy_set_header X-Client-IP       \$remote_addr;
        proxy_set_header X-Forwarded-Proto ${XFP};

        # websockets
        proxy_http_version 1.1;
        proxy_set_header Upgrade    \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 90s;
    }
}
EOF
)"

if [ "$CF" = 1 ]; then
    # Fetch first so a failure aborts before we touch anything (set -e doesn't
    # catch failures inside a process substitution).
    CF_RANGES="$(fetch_cf_ranges)" || exit 1
    REALIP_CONF="# Generated by scripts/_core/setup-host-proxy.sh. Restores the real visitor IP from Cloudflare.
# Source: https://www.cloudflare.com/ips/
"
    while IFS= read -r cidr; do
        [ -n "$cidr" ] && REALIP_CONF+="set_real_ip_from ${cidr};"$'\n'
    done <<< "$CF_RANGES"
    REALIP_CONF+="real_ip_header CF-Connecting-IP;"$'\n'
fi

# --- show plan & confirm ---------------------------------------------------

echo ""
print_info "Plan:"
echo "  • write  ${SITE_FILE}"
[ -n "$ENABLED_LINK" ] && echo "  • enable ${ENABLED_LINK}"
[ "$CF" = 1 ] && echo "  • write  ${REALIP_FILE} (Cloudflare real-IP restore)"
echo "  • patch  .env  ->  PUBLIC_BIND_HOST=127.0.0.1, TRUSTED_IP_HEADER=X-Client-IP"
echo "  • nginx -t, then reload"
echo ""
confirm "Proceed?" n || { print_warning "Aborted. Nothing changed."; exit 0; }

# --- apply -----------------------------------------------------------------

STAMP="$(date +%Y%m%d-%H%M%S)"
BACKED_UP=()    # files that had a prior version — restore on rollback
CREATED=()      # files we created fresh — remove on rollback
LINK_CREATED=0

backup() {
    # Record every target before writing, so rollback can revert precisely.
    local f="$1"
    if [ -e "$f" ]; then
        $SUDO cp "$f" "${f}.bak.${STAMP}"
        BACKED_UP+=("$f")
        print_info "Backed up ${f} -> ${f}.bak.${STAMP}"
    else
        CREATED+=("$f")
    fi
}

rollback() {
    local f
    for f in ${BACKED_UP[@]+"${BACKED_UP[@]}"}; do
        [ -e "${f}.bak.${STAMP}" ] && $SUDO mv "${f}.bak.${STAMP}" "$f"
    done
    for f in ${CREATED[@]+"${CREATED[@]}"}; do
        $SUDO rm -f "$f"
    done
    [ "$LINK_CREATED" = 1 ] && $SUDO rm -f "$ENABLED_LINK"
}

backup "$SITE_FILE"
echo "$SERVER_CONF" | $SUDO tee "$SITE_FILE" >/dev/null
print_success "Wrote ${SITE_FILE}"

if [ "$CF" = 1 ]; then
    backup "$REALIP_FILE"
    echo "$REALIP_CONF" | $SUDO tee "$REALIP_FILE" >/dev/null
    print_success "Wrote ${REALIP_FILE}"
fi

if [ -n "$ENABLED_LINK" ] && [ ! -e "$ENABLED_LINK" ]; then
    $SUDO ln -s "$SITE_FILE" "$ENABLED_LINK"
    LINK_CREATED=1
    print_success "Enabled ${ENABLED_LINK}"
fi

# Validate before reloading; roll everything back on failure.
if $SUDO nginx -t 2>/dev/null; then
    $SUDO nginx -s reload 2>/dev/null || $SUDO systemctl reload nginx
    print_success "nginx validated and reloaded"
else
    print_error "nginx -t failed. Rolling back all changes and aborting."
    rollback
    $SUDO nginx -t && print_info "Rolled back to a valid config."
    exit 1
fi

# Patch .env (after nginx is confirmed good).
set_env PUBLIC_BIND_HOST 127.0.0.1
set_env TRUSTED_IP_HEADER X-Client-IP
print_success "Patched .env (PUBLIC_BIND_HOST=127.0.0.1, TRUSTED_IP_HEADER=X-Client-IP)"

# --- next steps ------------------------------------------------------------

echo ""
print_success "Done. nginx now fronts ${DOMAIN} -> 127.0.0.1:${PUBLIC_PORT}."
echo ""
print_warning "Recreate the prod stack so PUBLIC_BIND_HOST takes effect (port rebind needs a container recreate):"
echo "    npm run start"
echo ""
if [ "$CF" = 1 ]; then
    print_info "Cloudflare: set SSL/TLS mode to Full (strict) and install an Origin Certificate for end-to-end TLS."
else
    print_info "No Cloudflare: issue a TLS cert for this domain (DNS must already point here):"
    echo "    sudo certbot --nginx -d ${DOMAIN}"
fi
